version: '3'

services:
  jupyter1:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./code:/home/jovyan/code
    environment:
      - JUPYTER_LAB_ENABLE=yes
    command: jupyter notebook --NotebookApp.token= --allow-root
  
  # jupyter2:
  #   build:
  #     context: .
  #   ports:
  #     - 8889:8888
  #   volumes:
  #     - ./code:/home/jovyan/code
  #   environment:
  #     - JUPYTER_LAB_ENABLE=yes
  #   command: jupyter notebook --NotebookApp.token= --allow-root

  # jupyter3:
  #   build:
  #     context: .
  #   ports:
  #     - 8890:8888
  #   volumes:
  #     - ./code:/home/jovyan/code
  #   environment:
  #     - JUPYTER_LAB_ENABLE=yes
  #   command: jupyter notebook --NotebookApp.token= --allow-root


  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
        - ./db:/data/db